---
title: "New Construction in Chicago by Community Area"
output: github_document
---

Libraries!

```{r load libraries, message=FALSE}
library(tidyverse)
library(lubridate)
library(data.table)
library(sf)
```

Then we have to deal with the fact that most of the construction permit dataset is useless.

```{r permit data wrangling}
# read in data
new_construction_bad_date <- fread("CSV/CSV_chicago_building-permits.csv") %>%  
  select("PERMIT_TYPE", "ISSUE_DATE", "REPORTED_COST", "COMMUNITY_AREA", "XCOORDINATE", "YCOORDINATE", "LATITUDE", "LONGITUDE") %>% # selects relevant columns
  filter(PERMIT_TYPE == "PERMIT - NEW CONSTRUCTION") %>% # only new construction
  filter(!is.na(COMMUNITY_AREA)) # community area has to have a value

# make ISSUE_DATE column actually dates
new_construction <- new_construction_bad_date %>% 
  mutate(ISSUE_DATE = mdy(ISSUE_DATE)) %>% 
  arrange(ISSUE_DATE) # sorts

new_construction
```

After cleaning the permit data, we need to import the community area shapefile.

```{r shapefile modifications}
community_areas <- st_read("SHP/SHP_chicago-communities/geo_export_e07d67fa-91ce-4d30-9da3-eb903021731c.shp", quiet = TRUE)

community_areas_fortified <- fortify(community_areas) # turns shapefile into dataframe

ggplot(data = community_areas) +
  geom_sf(data = community_areas_fortified) +
  theme_void()
```

Now it's time to join the data and community shapes.

```{r joining}
new_construction_totals <- new_construction %>% 
  group_by(COMMUNITY_AREA) %>% 
  summarize(total_permits = n()) %>% 
  filter(COMMUNITY_AREA != 0) # for some reason there were some community area "0" observations?

# joins have to be on the same variable class
new_construction_totals$COMMUNITY_AREA <- as.character(new_construction_totals$COMMUNITY_AREA)

chicago_community_choropleth_data <- left_join(community_areas_fortified, new_construction_totals, by = c("area_num_1" = "COMMUNITY_AREA"))

```

And finally we plot it!

```{r plot, fig.width = 10, fig.height = 6}
plot <- ggplot() +  
  geom_sf(
    data = chicago_community_choropleth_data,
    aes(fill = total_permits),
    color = "black"
  ) +
  labs(    
    title = "New Construction Permits per Community Area",
    subtitle = "(2006-2022)"
  ) +
  scale_fill_viridis_b(
    breaks = c(25, 50, 100, 250, 500, 1000, 1500), 
    name = "Permits Issued"
  ) +
  theme_void() +
  theme(
        plot.title = element_text(size = 20, 
                                  color = "white", 
                                  family = "Space Grotesk", 
                                  face = "bold", 
                                  hjust = 0.5),    
        plot.subtitle = element_text(size = 15, 
                                     color = "gray70", 
                                     family = "Space Grotesk", 
                                     face = "italic", 
                                     hjust = 0.5),    
        legend.title = element_text(color = "white", 
                                    family = "Space Grotesk", 
                                    face = "bold"),    
        legend.text = element_text(color = "white", 
                                   family = "Space Grotesk"),    
        plot.margin = margin(10, 10, 10, 0),
        legend.position = c(1.2, 0.5),
        plot.background = element_rect(fill = "gray10", color = NA)
  )
# Below sets the background to be completely gray; otherwise it isn't.
grid::grid.newpage()
grid::grid.draw(grid::rectGrob(gp = grid::gpar(fill = "gray10")))
print(plot, newpage = FALSE)
```

