---
title: "Addressing the US Housing Shortage"
format: gfm
---

```{r}
#| label: setup
#| message: false
#| warning: false
#| results: false
library(tidyverse)
library(here)
library(zoo)
library(plotly)
```

```{r}
#| label: Import Data
#| message: false
#| results: false

# housing permits
read_permits <- function(x) {
  file <- read_csv(here("data", "housing-permits", x)) 
  return(file)
}
# because you have to go into here(), the map function alone doesn't work
# it tries to search for the filename in the working directory, but it doesn't exist there
# so we make a function for it to search in the CSV folder

permit_list <- list.files(path = here("data", "housing-permits"), pattern = ".*_housing-permits.csv")
permit_file_list <- map(permit_list, read_permits)
housing_permits <- bind_rows(permit_file_list)

rm(permit_list, permit_file_list, read_permits)

# housing & transportation index
read_hti <- function(x) {
  file <- read_csv(here("data", "ht-index", x))
  return(file)
}

hti_list <- list.files(path = here("data", "ht-index"), pattern = ".*_hti.csv")
hti_file_list <- map(hti_list, read_hti)
ht_index <- bind_rows(hti_file_list)

rm(hti_list, hti_file_list, read_hti)
```

```{r}
#| label: Cleaning Data

boroughs <- str_subset(str_to_title(unique(housing_permits$Location)), "Borough")

total_housing_permits <- housing_permits %>% 
  filter(
    Series == "Total Units"
  ) %>% 
  mutate(
    Location = str_to_title(Location),
    Date = make_date(Year, Month, "01"),
    City = case_when(
      Location %in% boroughs ~ "New York",
      Location == "Jacksonville-Duval County" ~ "Jacksonville",
      Location == "Washington" ~ "Washington DC",
      TRUE ~ Location
    ),
    .after = Location
  ) %>% 
  group_by(
    City, Date
  ) %>% 
  summarize(
    Permits = sum(Permits),
  ) %>% 
  mutate(
    Permit_Avg = rollmean(Permits, k = 12, fill = NA, align = "right")
  ) %>% 
  filter(
    !is.na(Permit_Avg),
    Date <= "2023-04-01" # the rest of the 2023 months are "0" which messes up the data
  )

cities <- str_to_lower(unique(total_housing_permits$City))

cities_ht_index <- ht_index %>% 
  mutate(
    name = str_remove_all(name, '"'), # names were surrounded with quotes
    cbsa = str_remove_all(cbsa, '"'),
    name = if_else(name == "Washington", "Washington DC", name)
  ) %>% 
  filter(
    str_to_lower(name) %in% cities,
    population > 250000 # there were a lot of duplicate cities lol
  ) %>% 
  select(
    name, cbsa, population, ht_ami, ht_nmi, h_ami, h_nmi, t_ami, t_nmi, h_cost
  )
```

```{r}
#| label: Set Graph Theme
theme_update(
  plot.background = element_rect(color = "gray10",
                                       fill = "gray10"),
        panel.background = element_blank(),
        
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(linewidth = 0.15),
        panel.grid.minor.y = element_line(linewidth = 0.15),      
  
        plot.title.position = "plot",
        plot.title = element_text(color = "white",
                                  family = "Space Grotesk",
                                  face = "bold",
                                  size = 20),
        
        plot.caption.position = "plot",
        plot.caption = element_text(color = "gray75",
                                family = "Space Grotesk"),
  
        axis.ticks = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(color = "gray75",
                                    family = "Space Grotesk",
                                    face = "bold"),
        axis.text = element_text(color = "gray60",
                                 family = "Space Grotesk"),
        
        legend.background = element_rect(color = "gray10",
                                         fill = "gray10"),
        legend.title = element_text(family = "Space Grotesk",
                                    face = "bold",
                                    color = "gray75"),
        legend.text = element_text(family = "Space Grotesk",
                                   color = "gray60"),
        legend.key = element_blank(),
        
        plot.margin = margin(10, 10, 10, 10)
)
```

```{r}
#| label: Housing Permit Graph
#| fig-width: 8
#| fig-asp: 0.666
permit_key <- highlight_key(total_housing_permits, ~City)

plotly_permits <- ggplot(
  permit_key,
  aes(x = Date,
      y = Permit_Avg,
      color = fct_reorder2(City, Date, Permit_Avg),
      group = City,
      text = str_c("City: ", fct_reorder2(City, Date, Permit_Avg),
                   "\nAvg. Permits: ", round(Permit_Avg, digits = 2))
      )
  ) +
  geom_line(
  ) + 
  labs(
    title = "New York and Sunbelt Cities Lead the Way in Housing\nPermitting, While Most Northern Cities Fall Behind",
    y = "Monthly Housing Unit Permits, 12-mo. Moving Avg.",
    color = "City"
  ) +
  coord_cartesian(
    ylim = c(-5, 2505),
    xlim = c(as_date("2017-01-01"), as_date("2023-04-01"))
  ) +
  scale_x_date(
    date_breaks = "1 year",
    date_labels = "%Y"
  ) +
  scale_y_continuous(
    expand = c(0,0)
  ) +
  guides(
    color = guide_legend(nrow = 9)
  ) +
  theme(
    axis.text.x = element_text(vjust = 1),
    axis.ticks.x = element_line(color = "gray40"),
  )
# ggsave(here("national-market-comparison", "plots", "national_housing-permits_line-graph.png"), width = 10, height = 5)

font = list(
  family = "Space Grotesk",
  size = 12,
  color = "white"
)

label = list(
  bordercolor = "transparent",
  font = font
)

plot <- ggplotly(
  plotly_permits,
  tooltip = c("x", "text") # this is really janky, it *requires* the group = 1
  ) %>% 
  layout(
    plot_bgcolor='rgba(0,0,0,0)',
    font = font,
    yaxis = list(fixedrange = TRUE),
    xaxis = list(fixedrange = TRUE)
  ) %>% 
  style(
    hoverlabel = label
  ) %>% 
  config(
    displayModeBar = FALSE
  )

highlight <- highlight(
  plot, on = "plotly_hover", 
  off = "plotly_doubleclick", 
  selected = attrs_selected(showlegend = FALSE)
  )

```

```{r}
#| label: save widget
# library(htmlwidgets)
# saveWidget(highlight, "plot.html")
```


```{r}
#| label: Merging Dataframes + Calculating Housing Response Index

housing_response_index <- total_housing_permits %>% 
  left_join(
    cities_ht_index, 
    join_by(City == name)
  ) %>% 
  mutate(
    hri = (Permit_Avg/ht_nmi),
    .after = Permit_Avg,
    City = fct(City)
  )

```

```{r}
#| label: Housing Response Index Plot
#| fig-width: 10
#| fig-asp: 0.5
ggplot(
  housing_response_index,
  aes(x = Date,
      y = hri,
      color = fct_reorder2(City, Date, hri))
  ) +
  geom_line(
  ) + 
  labs(
    title = "Houston and New York Lead the Charge ",
    y = "Housing Response Index",
    color = "City"
  ) +
  coord_cartesian(
    xlim = c(as_date("2017-01-01"), as_date("2023-04-01")),
    ylim = c(0, 150)
  ) +
  scale_x_continuous(
    expand = c(0,0)
  ) +
  guides(
    color = guide_legend(nrow = 9)
  ) +
  theme(
    plot.title = element_text(size = 17)
  )

# ggsave(here("national-market-comparison", "plots", "HRI.png"), width = 10, height = 5)
```



